
title: QA Site for Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

repo_name: "This-should-be-overridden-by-github-actions-script"

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "This-should-be-overridden-by-github-actions-script"
repo: ucsb-cs156-s23/team02-s23-5pm-2
owner: ucsb-cs156-s23
repo_name: team02-s23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-team-qa-settup","number":65,"title":"update README with qa URL","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-2/pull/65"},{"author":{"id":"MDQ6VXNlcjU5NjY0ODg0","is_bot":false,"login":"LeonFeng0325","name":""},"headRefName":"Leon-team-prod-settup","number":63,"title":"add prod website url to README","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-2/pull/63"}]
