
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/team02-s23-5pm-2
owner: ucsb-cs156-s23
repo_name: team02-s23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjU2MDUxNjQ2","is_bot":false,"login":"AlejandroRR16","name":""},"headRefName":"Alejandro-vehicle-controller","number":77,"title":"Alejandro vehicle controller","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-2/pull/77"},{"author":{"id":"MDQ6VXNlcjc3NzA5OTIx","is_bot":false,"login":"Simon-Lai103","name":""},"headRefName":"Simon-EnergyDrinkDatabase","number":76,"title":"sl - added issue11 EnergyDrink","url":"https://github.com/ucsb-cs156-s23/team02-s23-5pm-2/pull/76"}]
